In [1]:
import numpy as np

In [2]:
#Crrear una función que regrese todos los numeros primos menores a un valor recibido como argumento

In [3]:
5%np.arange(2,5)

array([1, 2, 1])

In [4]:
(5%np.arange(2,5))==0

array([False, False, False])

In [5]:
divisibles=(5%np.arange(2,5))==0
divisibles

array([False, False, False])

In [6]:
divisibles.any()

np.False_

In [7]:
divisibles=(8%np.arange(2,8))==0
divisibles.any()

np.True_

In [15]:
def primos(n):
    primos = []
    for num in range(2, n):
        divisores = np.arange(2, int(np.sqrt(num)) + 1)
        if not (num % divisores == 0).any():
            primos.append(num)
    return primos

print(primos(25))

[2, 3, 5, 7, 11, 13, 17, 19, 23]


In [10]:
#Código que dio Chat

In [17]:
import numpy as np

def primos_menores(n):
    if n < 2:
        return []

    # Inicializamos un arreglo booleano: True = primo, False = no primo
    es_primo = np.ones(n, dtype=bool)
    es_primo[:2] = False  # 0 y 1 no son primos

    limite = int(np.sqrt(n)) + 1
    for i in range(2, limite):
        if es_primo[i]:
            # Marcamos como no primos todos los múltiplos de i
            es_primo[i*i:n:i] = False

    return np.nonzero(es_primo)[0].tolist()

# Ejemplo
print(primos_menores(33))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]


Comparando ambos códigos, llego a la conclusión de que mi código es mejor porque es más corto y está mas optimizado, entonces no tomaría en cuenta los cambios que me hizo Chat porque es un código más largo y más complejo, para al final llegar al mismo resultado que mi código.